package Percobaan_12;

class MyException extends Exception {
    private String Teks;

    MyException(String s) {
        Teks = "Exception generated by: " + s;
        System.out.println(Teks);
    }
}

class Eksepsi {
    static void tampil(String s) throws Exception {
        System.out.println("Tampil");
        if (s.equals("Amir")) {
            throw new MyException(s);
        }
        System.out.println("OK!");
    }

    public static void main(String[] args) {
        try {
            tampil("ali");
            tampil("amir");
        } catch (Exception e) {
            System.out.println("Tangkap:" + e);
        }
    }
}